### ISSUE TITLE
کمبود برخی حروف

### ISSUE THREAD

**Issue by rastikerdar** [nainemom/sentence-info#1]
به نظر میاد بسیاری از حالات حروف را فراموش نموده اید اضافه کنید:
ـک ـح ـب ـل ـو کـ چـ بـ صـ سـ ـد...
شاید بهتر باشه دوباره مرور بفرمایید.
![screenshot from 2016-04-04 19-44-03](https://cloud.githubusercontent.com/assets/3116038/14252688/a389a9fe-fa9d-11e5-8cb2-e4b1ab16b5eb.png)

**Comment by nainemom** [comment]
برای این برنامه، من برای حروف به جز "ه" دو تا حالت **وسط** و **تنها** در نظر گرفتم. مثلا حرف "ب":
**مبهوت**، **برجام**: در این دو، حالت **وسط**
**آب**، **سیب**: در این دو، حالت **تنها**

آقای برگی هم [اینجا](https://github.com/aziz) در لیست اغماض شدشون یه چنین چیزی گفتن.

به هر حال، توی این برنامه باید بین ـبـ و بـ تفاوت قائل شم؟ (یا از نظر طراحی فونت، بین این دو حالت فرق زیادی هست؟)

## 

بروزرسانی:
توی کامیتی که الان کردم، هردو حالت رو در نظر گرفتم.

**Comment by rastikerdar** [comment]
خیلی خوب شده. اتفاقا می خواستم بگم اگر مقدوره که کد رو به صورت یک کتابخانه در بیاورید که شد. به نظر من حتی می تونه تبدیل بشه به یک یا چند کتابخانه جامع در مورد زبان فارسی که هر نوع اطلاعاتی در مورد متن فارسی به ویژه در حوزه دستور زبان یا حتی در حالت ایده آلش برخی موارد حوزه مفهومی و معنایی ارائه بده.

به هر حال سپاس.
پس من ایشو رو می بندم.
